services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ../../app-data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - CADDY_TAILSCALE_IP=${TAILSCALE_WOLFETONE_IP}
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ~/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  rtl_433:
    image: hertzg/rtl_433:master
    container_name: rtl_433
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    command: '-f 868.3M -g 0 -F mqtt://mosquitto:1883,events=rtl_433[/model][/id]'
    depends_on:
      - mosquitto
