services:
  db:
    image: mariadb:10.11
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ../../app-data/nextcloud/db:/var/lib/mysql
      - /etc/nextcloud-db.cnf:/etc/mysql/conf.d/nextcloud-db.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 3
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    environment:
      NTFY_BASE_URL: "https://wolfetone.tailee21f7.ts.net:8081"
      NTFY_AUTH_DEFAULT_ACCESS: "write-only"
      NTFY_BEHIND_PROXY: "true"
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /var/lib/ntfy:/var/lib/ntfy
    command:
      - serve
    restart: unless-stopped
  app:
    image: nextcloud:stable
    container_name: nextcloud-app
    restart: unless-stopped
    volumes:
      - ../../app-data/nextcloud/html:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    depends_on:
      - app
      - ntfy
    ports:
      # UPDATE: Caddy now acts as the gateway for both services on the Tailscale IP
      - "100.83.211.123:443:443"
      - "100.83.211.123:8081:8081"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs

