# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 100.83.211.123
    - 172.16.0.0/12  # docker subnet

mqtt:
  sensor:
    - name: "Climote Sensor Value"
      state_topic: "rtl_433/raw"
      # Ensure it only processes messages from your specific flex decoder
      value_template: >
        {% if value_json.model == 'climote' %}
          {# Adjust the [x:y] index to the exact position of your MSB/LSB in the hex string #}
          {% set hex_val = value_json.data[4:8] %} 
          {{ int(hex_val, 16) }}
        {% else %}
          {{ states('sensor.climote_sensor_value') }}
        {% endif %}
        