# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 100.83.211.123
    - 172.16.0.0/12  # docker subnet

mqtt:
  sensor:
    - name: "Climote Raw NTC Decimal"
      state_topic: "rtl_433/raw"
      value_template: >
        {% if value_json.model == 'climote' and value_json.data is defined %}
          {% set hex_str = value_json.data %}
          
          {# Ensure the payload is long enough to avoid indexing errors on junk frames #}
          {% if hex_str | length >= 34 %}
            {# Extract the '6' or '5' (Index 28) #}
            {% set msb_nibble = hex_str[28] %}
            
            {# Extract the active byte e.g. 'd8', '1d' (Indices 32 and 33) #}
            {% set lsb_byte = hex_str[32:34] %}
            
            {# Combine into a 3-character hex string (e.g., '61d') and convert to decimal #}
            {% set combined_hex = msb_nibble ~ lsb_byte %}
            {{ int(combined_hex, 16) }}
          {% else %}
            {{ states('sensor.climote_raw_ntc_decimal') }}
          {% endif %}
        {% else %}
          {{ states('sensor.climote_raw_ntc_decimal') }}
        {% endif %}
